CREATE TABLE usuario (
  id BIGINT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(120) NOT NULL, email VARCHAR(160) NOT NULL UNIQUE,
  senha_hash VARCHAR(100) NOT NULL, perfil VARCHAR(20) NOT NULL, telefone VARCHAR(30), endereco VARCHAR(255),
  status VARCHAR(10) NOT NULL DEFAULT 'ATIVO', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE categoria (
  id BIGINT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(80) NOT NULL, descricao VARCHAR(255), ordem INT NOT NULL DEFAULT 0,
  status VARCHAR(10) NOT NULL DEFAULT 'ATIVO', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE prato (
  id BIGINT AUTO_INCREMENT PRIMARY KEY, categoria_id BIGINT NOT NULL, nome VARCHAR(120) NOT NULL,
  descricao VARCHAR(500), foto_url VARCHAR(255), preco_venda DECIMAL(10,2) NOT NULL, tempo_preparo_min INT NOT NULL DEFAULT 15,
  status VARCHAR(10) NOT NULL DEFAULT 'ATIVO', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_prato_categoria FOREIGN KEY (categoria_id) REFERENCES categoria(id));
CREATE TABLE pedido (
  id BIGINT AUTO_INCREMENT PRIMARY KEY, cliente_id BIGINT NOT NULL, status VARCHAR(20) NOT NULL,
  valor_total DECIMAL(10,2) NOT NULL, endereco_entrega VARCHAR(255) NOT NULL, observacoes VARCHAR(500),
  motivo_cancelamento VARCHAR(255), created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pedido_cliente FOREIGN KEY (cliente_id) REFERENCES usuario(id));
CREATE TABLE pedido_item (
  id BIGINT AUTO_INCREMENT PRIMARY KEY, pedido_id BIGINT NOT NULL, prato_id BIGINT NOT NULL,
  quantidade INT NOT NULL, preco_unitario DECIMAL(10,2) NOT NULL, observacoes VARCHAR(255),
  CONSTRAINT fk_item_pedido FOREIGN KEY (pedido_id) REFERENCES pedido(id),
  CONSTRAINT fk_item_prato FOREIGN KEY (prato_id) REFERENCES prato(id));
